In [1]:
import os
import yaml
import pytz
import requests
import numpy as np
import pandas as pd
from datetime import datetime
from dotenv import load_dotenv

# import functions from bookie_grabber
from bookie_grabber import *

# import betfair_api funcs
from betfair_api import *

load_dotenv()

True

In [ ]:
# ┌─────────────────────────────────────────────────────────┐
# │  1. SPORTS                                              │
# │  What sports are available?                             │
# │  GET /v3/sports                                         │
# │  Returns: Football, Basketball, Tennis, etc.            │
# └──────────────────┬──────────────────────────────────────┘
#                    │
#                    ↓
# ┌─────────────────────────────────────────────────────────┐
# │  2. LEAGUES                                             │
# │  What leagues exist in a sport?                         │
# │  GET /v3/leagues?sport=football                         │
# │  Returns: Premier League, La Liga, Bundesliga, etc.     │
# └──────────────────┬──────────────────────────────────────┘
#                    │
#                    ↓
# ┌─────────────────────────────────────────────────────────┐
# │  3. EVENTS                                              │
# │  What matches are coming up?                            │
# │  GET /v3/events?sport=football&league=premier-league    │
# │  Returns: Man Utd vs Liverpool, Chelsea vs Arsenal, etc.│
# └──────────────────┬──────────────────────────────────────┘
#                    │
#                    ↓
# ┌─────────────────────────────────────────────────────────┐
# │  4. ODDS                                                │
# │  What are the betting odds?                             │
# │  GET /v3/odds?eventId=123456&bookmakers=Bet365,Unibet   │
# │  Returns: Odds from multiple bookmakers                 │
# └─────────────────────────────────────────────────────────┘

In [ ]:
# "status": "pending" for events
# Example usage
df_totals, df_btts = main()

In [ ]:
# Hey mate, the volume is already available, listed under “depth” in the markets array.

In [ ]:
api_key = load_env()
odds = get_event_odds(api_key, 61300797)

In [ ]:
for bookmaker, markets in odds.get("bookmakers", {}).items():
    for m in markets:
        print(f"{bookmaker} - {m.get('name')}" )

In [ ]:
btts = []
for bookmaker, markets in odds.get("bookmakers", {}).items():
    for market in markets:
        if market.get("name") == "Both Teams to Score" or market.get("name") == "Both Teams To Score":
            for o in market.get("odds", []):
                    btts.append({
                        "bookmaker": bookmaker,
                        "market": market.get("name"),
                        "yes": o.get("yes"),
                        "no": o.get("no"),
                    })
btts

In [2]:
# confirm that 
dft = pd.read_csv(r"data/exports/english_premier_league/totals/totals_hdp_2.5_20251205.csv")
dfb= pd.read_csv(r"data/exports/english_premier_league/btts/btts_20251205.csv")

In [3]:
session_token = get_session_token()
print("SESSION TOKEN:", session_token)
# Pick a league from config (for example, first league)
league_name = LEAGUES[0]["name"]
df = get_ou_volume(session_token, league_name)

SESSION TOKEN: f/tuViBEIYTwcaPBjlwcC9gm93ywzWVijMB66XHSG58=

In [ ]:
ODDS_TO_BF_TEAM_NAME_MAP = {'Aston Villa': 'Aston Villa',
 'Arsenal FC': 'Arsenal',
 'Everton FC': 'Everton',
 'Nottingham Forest': 'Nottm Forest',
 'Newcastle United': 'Newcastle',
 'Burnley FC': 'Burnley',
 'AFC Bournemouth': 'Bournemouth',
 'Chelsea FC': 'Chelsea',
 'Manchester City': 'Man City',
 'Sunderland AFC': 'Sunderland',
 'Tottenham Hotspur': 'Tottenham',
 'Brentford FC': 'Brentford',
 'Leeds United': 'Leeds',
 'Liverpool FC': 'Liverpool',
 'Brighton & Hove Albion': 'Brighton',
 'West Ham United': 'West Ham',
 'Fulham FC': 'Fulham',
 'Crystal Palace': 'Crystal Palace',
 'Wolverhampton Wanderers': 'Wolves',
 'Manchester United': 'Man Utd'}

In [ ]:
df[df.line == 'Both teams to Score?']

,marketId,line,total_volume,event,kickoff
1,1.251156121,Both teams to Score?,1332.9918,Aston Villa v Arsenal,2025-12-06T12:30:00.000Z
8,1.251156677,Both teams to Score?,37.9890,Everton v Nottm Forest,2025-12-06T15:00:00.000Z
10,1.251156538,Both teams to Score?,1196.9349,Newcastle v Burnley,2025-12-06T15:00:00.000Z
12,1.251156260,Both teams to Score?,870.2697,Bournemouth v Chelsea,2025-12-06T15:00:00.000Z
13,1.251155843,Both teams to Score?,1572.7245,Man City v Sunderland,2025-12-06T15:00:00.000Z
18,1.251157094,Both teams to Score?,1413.6933,Tottenham v Brentford,2025-12-06T15:00:00.000Z
27,1.251156955,Both teams to Score?,834.7128,Leeds v Liverpool,2025-12-06T17:30:00.000Z
30,1.251155982,Both teams to Score?,116.1378,Brighton v West Ham,2025-12-07T14:00:00.000Z
32,1.251156399,Both teams to Score?,68.9832,Fulham v Crystal Palace,2025-12-07T16:30:00.000Z
37,1.251156816,Both teams to Score?,2.0100,Wolves v Man Utd,2025-12-08T20:00:00.000Z
38,1.251327270,Both teams to Score?,0.0000,Chelsea v Everton,2025-12-13T15:00:00.000Z
39,1.251327409,Both teams to Score?,0.0000,Liverpool v Brighton,2025-12-13T15:00:00.000Z
43,1.251327131,Both teams to Score?,0.0000,Burnley v Fulham,2025-12-13T17:30:00.000Z
44,1.251326349,Both teams to Score?,0.0000,Arsenal v Wolves,2025-12-13T20:00:00.000Z
46,1.251326044,Both teams to Score?,0.0000,West Ham v Aston Villa,2025-12-14T14:00:00.000Z
47,1.251326776,Both teams to Score?,0.0000,Nottm Forest v Tottenham,2025-12-14T14:00:00.000Z
51,1.251326491,Both teams to Score?,0.0000,Crystal Palace v Man City,2025-12-14T14:00:00.000Z
53,1.251326207,Both teams to Score?,0.0000,Sunderland v Newcastle,2025-12-14T14:00:00.000Z
54,1.251325686,Both teams to Score?,0.0000,Brentford v Leeds,2025-12-14T16:30:00.000Z
57,1.251326633,Both teams to Score?,0.0000,Man Utd v Bournemouth,2025-12-15T20:00:00.000Z

In [7]:
df.columns

Index(['marketId', 'line', 'total_volume', 'event', 'kickoff'], dtype='object')

In [17]:
dfb['betfair_home_team'] = dfb['home_team'].map(TEAM_NAME_MAP)
dfb['betfair_away_team'] = dfb['away_team'].map(TEAM_NAME_MAP)
dfb

,event_id,home_team,away_team,competition,match_time,odds_time,Bet365_no_odds,Bet365_yes_odds,Betfair_Exchange_no_odds,Betfair_Exchange_yes_odds,Yes RPD,No RPD,hours_until_KO,betfair_home_team,betfair_away_team
0,61300795,AFC Bournemouth,Chelsea FC,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-05 22:24:39.756591+08:00,2.375,1.533,2.56,1.60,4.277,7.497,24.588957,Bournemouth,Chelsea
1,61300797,Aston Villa,Arsenal FC,England - Premier League,2025-12-06 20:30:00+08:00,2025-12-05 22:24:39.756591+08:00,1.909,1.909,2.00,1.95,2.125,4.656,22.088957,Aston Villa,Arsenal
2,61300799,Brighton & Hove Albion,West Ham United,England - Premier League,2025-12-07 22:00:00+08:00,2025-12-05 22:24:39.756591+08:00,2.050,1.700,2.24,1.76,3.468,8.858,47.588957,Brighton,West Ham
3,61300801,Everton FC,Nottingham Forest,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-05 22:24:39.756591+08:00,1.909,1.909,2.00,1.95,2.125,4.656,24.588957,Everton,Nottm Forest
4,61300803,Fulham FC,Crystal Palace,England - Premier League,2025-12-08 00:30:00+08:00,2025-12-05 22:24:39.756591+08:00,1.950,1.800,2.08,1.87,3.815,6.452,50.088957,Fulham,Crystal Palace
5,61300805,Leeds United,Liverpool FC,England - Premier League,2025-12-07 01:30:00+08:00,2025-12-05 22:24:39.756591+08:00,2.200,1.615,2.42,1.67,3.349,9.524,27.088957,Leeds,Liverpool
6,61300807,Manchester City,Sunderland AFC,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-05 22:24:39.756591+08:00,1.800,1.950,1.87,2.08,6.452,3.815,24.588957,Man City,Sunderland
7,61300809,Newcastle United,Burnley FC,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-05 22:24:39.756591+08:00,1.750,2.000,1.84,2.12,5.825,5.014,24.588957,Newcastle,Burnley
8,61300811,Tottenham Hotspur,Brentford FC,England - Premier League,2025-12-06 23:00:00+08:00,2025-12-05 22:24:39.756591+08:00,2.100,1.666,2.32,1.71,2.607,9.955,24.588957,Tottenham,Brentford
9,61300815,Arsenal FC,Wolverhampton Wanderers,England - Premier League,2025-12-14 04:00:00+08:00,2025-12-05 22:24:39.756591+08:00,1.571,2.250,1.60,2.34,3.922,1.829,197.588957,Arsenal,Wolves
10,61300817,Brentford FC,Leeds United,England - Premier League,2025-12-15 00:30:00+08:00,2025-12-05 22:24:39.756591+08:00,2.000,1.750,2.04,1.75,1.000,1.980,218.088957,Brentford,Leeds
11,61300819,Burnley FC,Fulham FC,England - Premier League,2025-12-14 01:30:00+08:00,2025-12-05 22:24:39.756591+08:00,1.909,1.909,1.01,1.01,1.000,1.000,195.088957,Burnley,Fulham
12,61300821,Chelsea FC,Everton FC,England - Premier League,2025-12-13 23:00:00+08:00,2025-12-05 22:24:39.756591+08:00,1.909,1.909,1.94,1.87,1.000,1.611,192.588957,Chelsea,Everton
13,61300823,Crystal Palace,Manchester City,England - Premier League,2025-12-14 22:00:00+08:00,2025-12-05 22:24:39.756591+08:00,2.200,1.615,1.01,1.01,1.000,1.000,215.588957,Crystal Palace,Man City
14,61300825,Liverpool FC,Brighton & Hove Albion,England - Premier League,2025-12-13 23:00:00+08:00,2025-12-05 22:24:39.756591+08:00,2.250,1.571,2.38,1.60,1.829,5.616,192.588957,Liverpool,Brighton
15,61300829,Nottingham Forest,Tottenham Hotspur,England - Premier League,2025-12-14 22:00:00+08:00,2025-12-05 22:24:39.756591+08:00,2.050,1.700,2.20,1.71,1.000,7.059,215.588957,Nottm Forest,Tottenham
16,61300831,Sunderland AFC,Newcastle United,England - Premier League,2025-12-14 22:00:00+08:00,2025-12-05 22:24:39.756591+08:00,2.000,1.750,2.04,1.77,1.136,1.980,215.588957,Sunderland,Newcastle
17,61300833,West Ham United,Aston Villa,England - Premier League,2025-12-14 22:00:00+08:00,2025-12-05 22:24:39.756591+08:00,2.100,1.666,2.20,1.70,2.020,4.651,215.588957,West Ham,Aston Villa
18,64618978,Wolverhampton Wanderers,Manchester United,England - Premier League,2025-12-09 04:00:00+08:00,2025-12-05 22:24:39.756591+08:00,2.100,1.666,2.26,1.72,3.190,7.339,77.588957,Wolves,Man Utd
19,65586346,Manchester United,AFC Bournemouth,England - Premier League,2025-12-16 04:00:00+08:00,2025-12-05 22:24:39.756591+08:00,2.375,1.533,2.20,1.49,1.000,1.000,245.588957,Man Utd,Bournemouth